points:
  zones:
    matrix:
      anchor:
        rotate: 5
      columns:
        pinky:
        ring:
          key.splay: -5
          key.stagger: 12
          key.spread: u+3
        middle:
          key.stagger: 0
          key.spread: u+3
        index:
          key.spread: u+3
      rows:
        bottom:
        top:
    thumbcluster:
      anchor:
        ref: matrix_index_bottom
        shift: [5, -3u]
        rotate: -40
      columns:
        left:
        middle:
        right:
          rows.top.skip: true
      rows:
        bottom:
        top:
          shift: [u/2]
    start:
      mirror:
      columns:
        left:
  mirror:
    ref: thumbcluster_right_bottom
    distance: 4u


#    thumbcluster:
#      anchor:
#        ref: matrix_index_bottom
#        shift: [10, -2u]
#        rotate: -40
#      columns:
#        left:
#          key.skip: true # Skip all keys
#          rows:
#            middle.skip: false # Override this one key
#        middle:
#          #key.stagger: u/2
#        right:
#          key.skip: true
#          rows:
#            middle.skip: false
#      rows:
#        bottom:
#        middle:
#        top:



#    thumbcluster:
#      anchor:
#        ref: matrix_index_bottom
#        shift: [10, -2u]
#        rotate: -40
#      rows:
#        top:
#      columns:
#        c-left:
#        c-down:
#          key.spread: u + 2
#        c-right:
#          key.spread: 21.25
#    thumbcluster-top:
#      anchor:
#        ref: thumbcluster_c-left_top
#        shift: [10, u]
#      rows:
#        top:
#      columns:
#        c-up:
#        c-right:
#          key.spread: u + 2
